name: pwsh test

on:
    workflow_dispatch:

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
    
            - name: 'Run pwsh test'
              shell: pwsh
              run: |
                ./powershell/CreateWorkspaceParameterFile.ps1 -ParameterPath "./synapse.parameters.dev.json"
