name: pwsh test

on:
    push:
        branches: [ workspace_publish ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
    
            - name: 'Run pwsh test'
              shell: pwsh
              run: |
                ./powershell/OverrideWorkspaceParameters.ps1 -WorkspaceName "finops-synapse-dev"  -BicepParameterPath "./azuredeploy.parameters.dev.json" -WorkspaceTemplateParamaterPath "./s037-cost-management/TemplateParametersForWorkspace.json" -UpdatedParameterPath "./updated-deployment-parameters.json"
            
            - name: 'List'
              run: |
                ls

            - name: 'Read overwritten file'
              shell: pwsh
              run: |
                Write-Host "Hello test"
                $test = Get-Content -Path "./updated-deployment-parameters.json" -Raw | ConvertFrom-Json
                $test2 = $test | ConvertTo-Json
                Write-Host $test2

