name: pwsh test

on:
    push:
      branches: [ workspace_publish ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
    
            - name: 'Run pwsh test'
              shell: pwsh
              run: |
                ./powershell/CreateWorkspaceParameterFile.ps1 -ParameterPath "./synapse.parameters.dev.json" -WorkspaceTemplateParamaterPath "./s037-cost-management/TemplateParametersForWorkspace.json"
