name: FinOps environment deployment

on:
  workflow_dispatch:
  push:
    branches: [ workspace_publish ]

permissions:
  contents: read
  id-token: write

env:
  WORKSPACE_TEMPLATE_PARAMETER_PATH: ./s037-cost-management/TemplateParametersForWorkspace.json
  WORKSPACE_TEMPLATE_DEPLOYMENT_PATH: ./s037-cost-management/TemplateForWorkspace.json
  UPDATED_PARAMETER_PATH: updated-deployment-parameters.json
  UPDATED_DEPLOYMENT_PATH: updated-deployment-template.json
    
jobs:
  deploy-dev:
    name: Deploy Dev Environment
    runs-on: ubuntu-latest
    environment: dev
    env:
      RESOURCE_GROUP: finops-rg-dev
      SYNAPSE_WORKSPACE_NAME: finops-synapse-dev
      PARAMETER_FILE_PATH: azuredeploy.parameters.dev.json
    
    steps:
      - uses: actions/checkout@v2

      - name: 'Service Principal Authentication'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.S926_AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Update Bicep parameters
        uses: Azure/CLI@v1
        with: 
          inlineScript: |
            result=$(az synapse workspace show --name ${{ env.SYNAPSE_WORKSPACE_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} 2>/dev/null || echo "")
            exists=$(if [ -z "$result" ]; then echo false; else echo true; fi)
            echo "`jq --argjson new "$exists" '.parameters.workspaceExists.value = $new' ${{ env.PARAMETER_FILE_PATH }}`" > ${{ env.PARAMETER_FILE_PATH }}

      - name: Ensure Azure Infrastructure
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
              --template-file azuredeploy.bicep \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --parameters ${{ env.PARAMETER_FILE_PATH }}
      
      - name: 'Override Synapse ARM Template parameters'
        shell: pwsh
        run: |
          ./powershell/OverrideWorkspaceParameters.ps1 -SubscriptionId ${{ secrets.S926_AZURE_SUBSCRIPTION_ID }} -ResourceGroupName ${{ env.RESOURCE_GROUP }} -WorkspaceName ${{ env.SYNAPSE_WORKSPACE_NAME }} -BicepParameterPath ${{ env.PARAMETER_FILE_PATH }} -WorkspaceTemplateParamaterPath ${{ env.WORKSPACE_TEMPLATE_PARAMETER_PATH }} -UpdatedParameterPath ${{ env.UPDATED_PARAMETER_PATH }}
      
      - name: 'Clean ARM Template'
        shell: pwsh
        run: |
          ./powershell/CleanArmTemplate.ps1 -ARMTemplatePath ${{ env.WORKSPACE_TEMPLATE_DEPLOYMENT_PATH }} -UpdatedTemplatePath ${{ env.UPDATED_DEPLOYMENT_PATH }} -WorkspaceName ${{ env.SYNAPSE_WORKSPACE_NAME }} -BicepParameterPath ${{ env.PARAMETER_FILE_PATH }}

      - name: Synapse workspace deployment
        uses: Azure/synapse-workspace-deployment@V1.8.0
        with:
          TargetWorkspaceName: ${{ env.SYNAPSE_WORKSPACE_NAME }}
          TemplateFile: ${{ env.UPDATED_DEPLOYMENT_PATH }}
          ParametersFile: ${{ env.UPDATED_PARAMETER_PATH }}
          environment: 'Azure Public'
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          clientId: ${{ secrets.AZURE_SP_CLIENTID }}
          clientSecret: ${{ secrets.AZURE_SP_CLIENTSECRET }}
          subscriptionId: ${{ secrets.S926_AZURE_SUBSCRIPTION_ID }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          operation: 'deploy'

#   deploy-prod:
#     needs: deploy-test
#     name: Deploy Prod Environment
#     runs-on: ubuntu-latest
#     environment: prod
#     env:
#       RESOURCE_GROUP: finops-cicd-test
#       SYNAPSE_WORKSPACE_NAME: finops-synapse-prod
#       PARAMETER_FILE_PATH: azuredeploy.parameters.prod.json

#     steps:
#       - uses: actions/checkout@v2

#       - name: 'Service Principal Authentication'
#         uses: azure/login@v1
#         with:
#           creds: ${{secrets.AZURE_CREDENTIALS}}
#           enable-AzPSSession: true

#       - name: Update Bicep parameters
#         uses: Azure/CLI@v1
#         with: 
#           inlineScript: |

#             result=$(az synapse workspace show --name ${{ env.SYNAPSE_WORKSPACE_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} 2>/dev/null || echo "")
#             echo "$result"
#             exists=$(if [ -z "$result" ]; then echo false; else echo true; fi)
#             echo "$exists"
#             echo "`jq --argjson new "$exists" '.parameters.workspaceExists.value = $new' ${{ env.PARAMETER_FILE_PATH }}`" > ${{ env.PARAMETER_FILE_PATH }}

#       - name: Deploy Azure Resources
#         uses: Azure/CLI@v1
#         with:
#           inlineScript: |
#             az deployment group create \
#               --template-file azuredeploy.bicep \
#               --resource-group ${{ env.RESOURCE_GROUP }} \
#               --parameters ${{ env.PARAMETER_FILE_PATH }}

#       - name: Synapse workspace deployment
#         uses: Azure/synapse-workspace-deployment@V1.8.0
#         with:
#           TargetWorkspaceName: ${{ env.SYNAPSE_WORKSPACE_NAME }}
#           TemplateFile: './finops-synapse-test/TemplateForWorkspace.json'
#           ParametersFile: './synapse.parameters.prod.json'
#           environment: 'Azure Public'
#           resourceGroup: ${{ env.RESOURCE_GROUP }}
#           clientId: ${{ secrets.CLIENTID }}
#           clientSecret: ${{ secrets.CLIENTSECRET }}
#           subscriptionId: ${{ secrets.SUBID }}
#           tenantId: ${{ secrets.TENANTID }}
#           operation: 'deploy'
