name: Synapse Workspace Validation

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            # - name: Service Principal Authentication
            #   uses: azure/login@v1
            #   with:
            #     creds: ${{ secrets.S037_AZURE_CREDENTIALS }}
            #     enable-AzPSSession: true

            - name: Validate synapse workspace
              uses: Azure/synapse-workspace-deployment@V1.8.0
              with:
                TargetWorkspaceName: 'targetworkspace'
                ArtifactsFolder: '$GITHUB_WORKSPACE'
                operation: 'validate'

