name: FinOps Synapse workspace validation

on:
    pull_request:
        types: [opened, edited]

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            
            - name: List
              run: ls

            - name: Service Principal Authentication
              uses: azure/login@v1
              with:
                creds: ${{ secrets.S037_AZURE_CREDENTIALS }}
                enable-AzPSSession: true

            - name: Validate synapse workspace
              uses: Azure/synapse-workspace-deployment@V1.8.0
              with:
                TargetWorkspaceName: 'targetworkspace'
                ArtifactsFolder: './'
                operation: 'validate'

