name: FinOps Synapse workspace validation

on:
    pull_request:
      types:
        - opened 
    push:
      branches:
        - '*'

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            
